<a href="https://colab.research.google.com/github/gnbhub/GnB20222_AI_1/blob/master/1109/1109_woodahyeon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.array([1,2,3])
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
array = np.array([[1,2,3],[4,5,6]])

array([1, 2, 3])

In [ ]:
array[0]

array([1, 2, 3])

In [ ]:
array[1]

In [ ]:
array[0, :2]

array([1, 2])

In [ ]:
array[0]

array([1, 2, 3])

In [ ]:
array[0, :2]

array([1, 2])

In [ ]:
array.ndim

2

In [ ]:
array.shape

(2, 3)

In [ ]:
array.dtype

dtype('int32')

In [ ]:
array.sum()

21

In [ ]:
array.min()

1

In [ ]:
array.max()

6

In [ ]:
array.std()

1.707825127659933

In [ ]:
array.var()

2.9166666666666665

In [ ]:
nums = np.array([1,2,2,3])

In [ ]:

np.unique(nums)

array([1, 2, 3])

In [ ]:
np.arange(3,8,2)

array([3, 5, 7])

In [ ]:
np.where(nums == 2,1,0)

array([0, 1, 1, 0])

In [ ]:
import pandas as pd

In [ ]:
ser = pd.Series([1,2,3])

In [ ]:
ser

0    1
1    2
2    3
dtype: int64

In [ ]:
ser.values

array([1, 2, 3], dtype=int64)

In [ ]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
pd.Series([1,2,3,3,4])

0    1
1    2
2    3
3    3
4    4
dtype: int64

In [ ]:
pd.Series([1,2,3], index=['a','b','c'])

a    1
b    2
c    3
dtype: int64

In [ ]:
ser = pd.Series([1,2,3,3,4])
ser

0    1
1    2
2    3
3    3
4    4
dtype: int64

In [ ]:
ser = pd.Series([2,4,4,6,7,8])
ser

0    2
1    4
2    4
3    6
4    7
5    8
dtype: int64

In [ ]:
ser.idxmax()

5

In [ ]:
ser.idxmin()

0

In [ ]:
ser.isin([6,7])

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [ ]:
ser.isin([6,7]).sum()

2

In [ ]:
ser = pd.Series([1,2,3,3,4])
ser[0]

1

In [ ]:
ser[1:3]

1    2
2    3
dtype: int64

In [ ]:
df = pd.DataFrame({'aa':[1,2,3], 'bb':[2,3,4]})
df

aa  bb
0   1   2
1   2   3
2   3   4

In [ ]:
df['aa']

0    1
1    2
2    3
Name: aa, dtype: int64

In [ ]:
df.iloc[1,1]

3

In [ ]:
df.loc[1,'aa']

2

In [ ]:
df = pd.read_csv("iris_missing.csv")
df.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2     NaN
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2     NaN